# Question 14



**Part-A**

In this case, we have for the voltages $V_1$ and $V_{N-1}$ , which are connected to 3 wires.

$$\frac{V_1-V_+}{R}+\frac{V_1 -V_2}{R} +\frac{V_1- V_3}{R}=0$$
$$\frac{V_N}{R}+\frac{V_N -V_{N-1}}{R} +\frac{V_N- V_{N-2}}{R}=0$$

which translates into:
$$3V_1 - V_2 -V_3 -V_+=0$$
$$-V_{N-2} -V_{N-1} +3V_N=0$$

If we treat $V_+=V_0$ and $V_{N+1}=0$, then for all $2 \leq i \leq V_{N-1}$, we must have:

$$\frac{V_i-V_{i-2}}{R}+\frac{V_i -V_{i-1}}{R} +\frac{V_i- V_{i+1}}{R}+\frac{V_i-V_{i+2}}{R}=0\\ \implies -V_{i-2} -V_{i-1} +4V_i -V_{i+1} - V_{i+2}=0$$

which generates all the equations we need.




**Part-B**

This case the equations are represented by the matrix:

$$\begin{pmatrix}
3 & -1 & -1 & 0 & 0 & 0\\
-1 & 4 & -1 & -1 & 0 & 0\\
-1 & -1 & 4 & -1 & -1 & 0\\
0 & -1 & -1 & 4 & -1 & -1\\
0 & 0 & -1 & -1 & 4 & -1\\
0 & 0 & 0 & -1 & -1 & 3\\
\end{pmatrix}\begin{pmatrix}V_1\\ V_2\\ V_3\\ V_4\\ V_5\\ V_6 \end{pmatrix}= \begin{pmatrix} 5 \\\ 5 \\ 0 \\ 0 \\ 0 \\ 0 \end{pmatrix}$$ 



In [13]:
import numpy as np
import math

N=6
Vp=5

def create_mat(N):
  A=np.zeros([N,N])
  A[0][0]=A[N-1][N-1]=3
  A[0][:3]=[3, -1, -1]
  A[N-1][N-3:N]=[-1, -1, 3]
  A[1][:4]=[-1, 4, -1, -1]
  A[N-2][N-4:N]=[-1, -1, 4, -1]
  for i in range(2,N-2):
    A[i, max(0, i-2):min(N, i+3)]=[-1, -1, 4, -1, -1]
  return np.matrix(A)

sol=np.zeros(N)
sol[1]=Vp
sol[0]=Vp

#gaussian is used in linalg. solve
V=np.linalg.solve(create_mat(N),sol)
print('the voltages are:', V)


the voltages are: [3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


In [14]:
#part b
# In these case we modify the algorithm according to the banded Gaussian approach. We modify the previous program.


def gauss_band(A,v):
  for m in range(N):

    # Divide by the diagonal element
    div = A[m,m]
    A[m,m:min(m+3,N)] /= div
    v[m] /= div

    # Now subtract from the lower rows
    for i in range(m+1,min(m+3,N)):
        mult = A[i,m]
        A[i,m:min(m+3,N)] -= mult*A[m,m:min(m+3,N)]
        v[i] -= mult*v[m]

# Backsubstitution
    x = empty(N,float)
    for m in range(N-1,-1,-1):
      x[m] = v[m]
      for i in range(m+1,min(m+3, N)):
        x[m] -= A[m,i]*x[i]


  return x


N=10000
v=np.zeros(N)
v[0]=Vp
v[1]=Vp





In [15]:
m=create_mat(10000)
print(m)

[[ 3. -1. -1. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [-1. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1. -1.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ... -1. -1.  3.]]


In [16]:
from numpy import empty

v=np.zeros(N)
v[0]=Vp
v[1]=Vp
V=gauss_band(m,v)

In [ ]:
print(V)

[6.66666667 5.         0.         ... 0.         0.         0.        ]


In [4]:
import numpy as np

V=np.zeros([10000, 10000])
print(V)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
